openapi: 3.0.1
info:
  title: Defo
  description: Ask any question or provide a prompt.
  version: v2
servers:
  - url: https://zambrano.uk
paths:
  /defo:
    post:
      summary: Ask any question or provide a prompt.
      operationId: defo
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                api_key:
                  type: string
                input_text:
                  type: string
              required:
                - api_key
                - input_text
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: array
                    items:
                      type: string
              example:
                response: []
