openapi: 3.0.1
info:
  title: GPT-Defeater Plugin
  description: Plugin for defeating AI detection software. Ask a question or prompt and get a response.
  version: v1
servers:
  - url: http://localhost:5001
paths:
  /defeat:
    post:
      summary: Generate a response to defeat AI detection software
      operationId: defeatAI
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                api_key:
                  type: string
                input_text:
                  type: string
              required:
                - api_key
                - input_text
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: array
                    items:
                      type: string
              example:
                response: []
